# Nom du projet sur SonarCloud
sonar.projectKey=BobApp_Back
sonar.projectName=BobApp_Back
sonar.organization=juliodan57
sonar.host.url=https://sonarcloud.io

# Dossier des sources et classes
sonar.sources=src/main/java,src/main/resources
sonar.java.binaries=target/classes

# Encoding
sonar.sourceEncoding=UTF-8

# Tests
sonar.tests=src/test/java
sonar.junit.reportPaths=target/surefire-reports

# Coverage Jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions optionnelles
sonar.exclusions=**/.DS_Store