# Nom du projet sur SonarCloud
sonar.projectKey=BobApp_Front
sonar.organization=juliodan57
sonar.host.url=https://sonarcloud.io

# Dossier des sources
sonar.sources=src

# Rapport de coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8