name: CI Frontend


on:
  push:
    paths:
      - 'front/**'
  pull_request:
    paths:
      - 'front/**'

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: front

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm ci

      - name: Run tests
        run: npm run test -- --watch=false --code-coverage

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: front-coverage
          path: front/coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=BobApp_Front
            -Dsonar.organization=juliodan57
            -Dsonar.sources=front/src
            -Dsonar.javascript.lcov.reportPaths=front/coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}